//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LittleSeagull.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string UserPhone { get; set; }
        public System.DateTime Birthday { get; set; }
        public bool IsGraduate { get; set; }
        public decimal StudentMoney { get; set; }
        public int Sex { get; set; }
    }
}
